language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - pypy
  - pypy3.5
install:
  - pip install -q pytest
  - pip install -r requirements.txt
script:
    - py.test --cov=./
    - flake8
after_success:
    - codecov
